version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.google.cloud:google-cloud-datastore
    versions:
    - 1.105.7
    - 1.105.8
    - 1.105.9
    - 1.106.0
    - 1.106.1
    - 1.106.2
  - dependency-name: com.auth0:java-jwt
    versions:
    - 3.12.1
    - 3.13.0
    - 3.14.0
  - dependency-name: org.eclipse.jetty:jetty-servlet
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: org.eclipse.jetty:jetty-util
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: org.eclipse.jetty:jetty-jmx
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: org.eclipse.jetty:jetty-server
    versions:
    - 11.0.0
    - 11.0.1
