import com.fcs.pokerserver.events.PlayerAction;
import com.fcs.pokerserver.events.PlayerEvent;
import com.fcs.pokerserver.events.PlayerListenner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library implements PlayerListenner {
    public boolean someLibraryMethod() {
        return true;
    }

	@Override
	public void actionPerformed(PlayerEvent event) {
		if(event.getAction()==PlayerAction.BET)
		{
			
			System.out.println(event.getSource().getName()+" bet "+event.getSource().getLastBet());
		}
		
	}
}
